<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/cti.proto

namespace GPBMetadata\Grpc;

class Cti
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a0e677270632f6374692e70726f746f120363746922260a0f4167656e74436d645265717565737412130a0b6a736f6e5265717565737418012001280922220a0d4167656e74436d645265706c7912110a096a736f6e5265706c79180120012809323d0a0343746912360a084167656e74436d6412142e6374692e4167656e74436d64526571756573741a122e6374692e4167656e74436d645265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

