<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/cti.proto

namespace Cti;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cti.AgentCmdRequest</code>
 */
class AgentCmdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string jsonRequest = 1;</code>
     */
    protected $jsonRequest = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $jsonRequest
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Cti::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string jsonRequest = 1;</code>
     * @return string
     */
    public function getJsonRequest()
    {
        return $this->jsonRequest;
    }

    /**
     * Generated from protobuf field <code>string jsonRequest = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonRequest($var)
    {
        GPBUtil::checkString($var, True);
        $this->jsonRequest = $var;

        return $this;
    }

}

