<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/cti.proto

namespace Cti;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cti.AgentCmdReply</code>
 */
class AgentCmdReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string jsonReply = 1;</code>
     */
    protected $jsonReply = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $jsonReply
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc\Cti::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string jsonReply = 1;</code>
     * @return string
     */
    public function getJsonReply()
    {
        return $this->jsonReply;
    }

    /**
     * Generated from protobuf field <code>string jsonReply = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJsonReply($var)
    {
        GPBUtil::checkString($var, True);
        $this->jsonReply = $var;

        return $this;
    }

}

